version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flask-api:
    build:
      context: ./flask-api
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    volumes:
      - flask_data:/app/data

  golang-api:
    build:
      context: ./golang-api
    container_name: golang-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - flask-api
    environment:
      FLASK_API_URL: http://flask-api:5000
      REDIS_HOST: redis-server
      REDIS_PORT: 6379

volumes:
  redis_data:
  flask_data:
