# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/features.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/features.proto\"$\n\x0e\x46\x65\x61tureRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\"!\n\x0f\x46\x65\x61tureResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"(\n\x12SearchImageRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\"N\n\x13SearchImageResponse\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x32H\n\x10\x46\x65\x61tureExtractor\x12\x34\n\x0f\x45xtractFeatures\x12\x0f.FeatureRequest\x1a\x10.FeatureResponse2W\n\x0f\x46\x65\x61tureSearcher\x12\x44\n\x17SearchImageAcrossVideos\x12\x13.SearchImageRequest\x1a\x14.SearchImageResponseB\"Z video_search_project/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z video_search_project/proto;proto'
  _globals['_FEATUREREQUEST']._serialized_start=24
  _globals['_FEATUREREQUEST']._serialized_end=60
  _globals['_FEATURERESPONSE']._serialized_start=62
  _globals['_FEATURERESPONSE']._serialized_end=95
  _globals['_SEARCHIMAGEREQUEST']._serialized_start=97
  _globals['_SEARCHIMAGEREQUEST']._serialized_end=137
  _globals['_SEARCHIMAGERESPONSE']._serialized_start=139
  _globals['_SEARCHIMAGERESPONSE']._serialized_end=217
  _globals['_FEATUREEXTRACTOR']._serialized_start=219
  _globals['_FEATUREEXTRACTOR']._serialized_end=291
  _globals['_FEATURESEARCHER']._serialized_start=293
  _globals['_FEATURESEARCHER']._serialized_end=380
# @@protoc_insertion_point(module_scope)
